$axure.loadCurrentPage({
  "url":"indexen.html",
  "generationDate":new Date(1465358669824.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a166b72bdc5f47cabb687bc3d091082b",
    "type":"Axure:Page",
    "name":"indexEN",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb0eb4cef6fa441b841dc67a9ae27cc3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":930},
            "size":{
              "width":1024,
              "height":790}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393e06cb22904212bc91faea014cc2c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":930},
                "size":{
                  "width":1024,
                  "height":790}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u30.png"}},
{
          "id":"e576bd898dd04563aca8518d6384603d",
          "label":"beijing",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c74daa4b3d482cb005af3ceeb7288b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/beijing_u0.jpg"}},
{
          "id":"2c6b9c8861924059bebe4e2b8bdccdb1",
          "label":"logo",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":20},
            "size":{
              "width":33,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e322d3cf9d4130a2b881206bb29378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":20},
                "size":{
                  "width":33,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/logo_u2.png"}},
{
          "id":"9f4c9bcf679c47b1949617b425c5950f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":257,
              "y":24},
            "size":{
              "width":133,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef67ef7ebc444280bb56e41cb1038a82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":257,
                  "y":24},
                "size":{
                  "width":133,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u4.png"}},
{
          "id":"4b53ee0af5034dd7986729a1e43649b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":688,
              "height":266},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f8e3e1ef71e4a4cacde53d77ee94fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":688,
                  "height":266},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u6.png"}},
{
          "id":"20ba5152d12e4777a2a8c50feabb45b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":320},
            "size":{
              "width":54,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d4a7cd1c5124bc1a1151ba4b977aeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":320},
                "size":{
                  "width":54,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u8.png"}},
{
          "id":"3420862106944d12bcc3e87679f1d9d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":619,
              "y":270},
            "size":{
              "width":200,
              "height":286},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321fab54de0d4458b968600fd2911b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":619,
                  "y":270},
                "size":{
                  "width":200,
                  "height":286},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u10.png"}},
{
          "id":"bc4218edc9804759bab9f6b4c9b48805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF83F63,
              "opacity":1},
            "location":{
              "x":218,
              "y":387},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0f939b075744e2f8cb1b4c6cb888415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF83F63,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":387},
                "size":{
                  "width":105,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e793fe0fd49c4982971110bccb20d1f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":221,
              "y":430},
            "size":{
              "width":379,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d3f6c3e06648a18ad4d0eb8f923a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":430},
                "size":{
                  "width":379,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cac348de07c4345b291ab15ad6a07af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":614},
            "size":{
              "width":688,
              "height":266},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8b7376232c434cabc09d7d2cc8e343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":614},
                "size":{
                  "width":688,
                  "height":266},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u6.png"}},
{
          "id":"297738ec169d4295bd8b8a6293df732a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":651},
            "size":{
              "width":54,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e098d68bf6ca46548b47e9073da915f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":651},
                "size":{
                  "width":54,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u20.png"}},
{
          "id":"efa51a4c33574e97af98ca0100d5e69e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":199,
              "y":590},
            "size":{
              "width":201,
              "height":290},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5b39694f3e4eff96eab448af197715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":590},
                "size":{
                  "width":201,
                  "height":290},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u22.png"}},
{
          "id":"1dbd9c74552a4de1a316f79f0e2a8f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF83F63,
              "opacity":1},
            "location":{
              "x":694,
              "y":720},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf834d3f0494567bf2318f77fbfb59b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF83F63,
                  "opacity":1},
                "location":{
                  "x":694,
                  "y":720},
                "size":{
                  "width":105,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2ec4a0c59c476d9bef08ba46956d94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":440,
              "y":771},
            "size":{
              "width":360,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd61b67113f42fbbb54644cc07fbf8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":771},
                "size":{
                  "width":360,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09df7b73ba074340a7d73dc938cab1ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":1035},
            "size":{
              "width":167,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7055122a2ff84bc8b397b15390f9ba1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":173,
                  "y":1035},
                "size":{
                  "width":167,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u32.png"}},
{
          "id":"b6fbcd9c46574a86aa08999de0c7738e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":1035},
            "size":{
              "width":167,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da35dffaf2a845beb0c71e7f11c4ab46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":1035},
                "size":{
                  "width":167,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u34.png"}},
{
          "id":"4cca77058d8f474ab49b3c489d294116",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":86.5,
              "y":1196},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad58c1ee55045b98bef5bd5b49b0a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":86.5,
                  "y":1196},
                "size":{
                  "width":340,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13829491c8304045acf25957e864568c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":107,
              "y":1234},
            "size":{
              "width":300,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f246db1a02f240e5967994d7964e6c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":1234},
                "size":{
                  "width":300,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"162148ee7877490ea99181d6a8f5503a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":618,
              "y":1235},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ae945ed25b4b4b9bee6a9baa1d66e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":618,
                  "y":1235},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a63b55e5078464a8f91c7b07f1a76c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":1201},
            "size":{
              "width":215,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11df8e409980400a8546c665a9840e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":1201},
                "size":{
                  "width":215,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a90827473b3a43a3b8cf6bf4873a8e9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":1738},
            "size":{
              "width":80,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6669c043a1e347f3a1013b1a2160e02d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":1738},
                "size":{
                  "width":80,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/indexen/u40.png"}},
{
          "id":"726531201bd04d549fe372dbb855a3ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":1779},
            "size":{
              "width":243,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD6313E}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/u46_line.png"}},
{
          "id":"22d200b19e1b48ed9d6e5edeedf04508",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":1779},
            "size":{
              "width":243,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD6313E}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/u46_line.png"}},
{
          "id":"a934c7e518b44a459c6c5e87845d3c3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":1824},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d294c4abbe465599b3997e160f8a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":1824},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u48.png"}},
{
          "id":"384ec736baf1450383a86727fa3107e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":1824},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e611dec862d41aa842f569f98ff7e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":1824},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u50.png"}},
{
          "id":"4df2e9b6539e47be9445591802ced6e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":1824},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4e069ae302451f9b95bdfbd8718964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":1824},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u52.png"}},
{
          "id":"f884585810c74401a67af4e05a79b091",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":2002},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935cebdad52942b5ade580d6fd329a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":2002},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u54.png"}},
{
          "id":"c0b208a463884f13bcd93f3acea0d1d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":2002},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb4903b3d0049dca87d20ee3dd6683d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":2002},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u56.png"}},
{
          "id":"7b82a1e6d4e248f184a8c332ca1113db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":168,
              "y":1962},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a7feddeeb44e9693d4cdc7159b84d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":168,
                  "y":1962},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e7477ee562c4840b68585c3d91e6559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":440,
              "y":1962},
            "size":{
              "width":145,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98540b4feb3144609ab71f665b7ed899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":440,
                  "y":1962},
                "size":{
                  "width":145,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6e7faac5b99490ebd05c4fb3e6d7a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":680,
              "y":1962},
            "size":{
              "width":173,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9342a4c624684ee5b4a3d30de2922aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":680,
                  "y":1962},
                "size":{
                  "width":173,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5475f03be7475daf2d1cd9cf6f1cb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":2139},
            "size":{
              "width":151,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95c09805724546ddb398267eee0a64c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":2139},
                "size":{
                  "width":151,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b480ac491fa405498ab472cf887e7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":433,
              "y":2140},
            "size":{
              "width":156,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ade7b13fa34059bec55ffcbf84eeb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":433,
                  "y":2140},
                "size":{
                  "width":156,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"277eba61411a46a196878da32013b4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":2366},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6065835e30cf48e2a006cd5570d825f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":2366},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u68.png"}},
{
          "id":"ab9497544dbb4e17b07e0e461e200cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":2408},
            "size":{
              "width":398,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5632cc953b3d42faad569fae4af409b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":2408},
                "size":{
                  "width":398,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c45b794ce004741a5471afd972edd84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":2466},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22db71cc8994f239ad172c1c9d0cefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":2466},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u72.png"}},
{
          "id":"58676220c8d74c9a9620118578205313",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":857,
              "y":21},
            "size":{
              "width":58,
              "height":22},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0204de864a7450396b123d05c954d7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":857,
                  "y":21},
                "size":{
                  "width":58,
                  "height":22},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u74.png"}},
{
          "id":"e9095ddf28a44fd7980ca4978a6dbac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":891,
              "y":22},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ca27a0ba93447ba0c48845a34b6c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":891,
                  "y":22},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u76.png"}},
{
          "id":"e1b03a7d62e44494a0d650eba7096426",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":864,
              "y":24},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5589bd53c68042d487b6a4dfa3bd6160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":864,
                  "y":24},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eac53b74024c41269ca3ce48c09ad5bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":892,
              "y":24},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dca05cdc02f49359740835cba85e5ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":24},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dca10ec8b70f4ebe8338c4c150c05b36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":476,
              "y":24},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5403561c3a14e8781a475d9e930a56f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":476,
                  "y":24},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 indexEN",
                      "target":{
                        "targetType":"page",
                        "url":"indexen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3c9ee911944a4ad4aa741b593fb80ea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":540,
              "y":24},
            "size":{
              "width":112,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fac24f7331c44f0a6c44be25a5023a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":540,
                  "y":24},
                "size":{
                  "width":112,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwuEN",
                      "target":{
                        "targetType":"page",
                        "url":"fuwuen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["932de16c15734cca93dd2bd225b874b5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["932de16c15734cca93dd2bd225b874b5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8df3b9e3e2f145bf9b384b1b036fb39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":650,
              "y":24},
            "size":{
              "width":123,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba1a364badc64c6fb2db72a0d4ee3f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":650,
                  "y":24},
                "size":{
                  "width":123,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuanduiEN",
                      "target":{
                        "targetType":"page",
                        "url":"tuanduien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["be9b7ce18b6c4ae48b1eb7df3305a4cd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["be9b7ce18b6c4ae48b1eb7df3305a4cd"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9e0070937b6e4d9fbe549b0c781fb8fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":773,
              "y":24},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817a1ae3cbea43bba77ddf0cd6ef03bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":773,
                  "y":24},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 lianxiEN",
                      "target":{
                        "targetType":"page",
                        "url":"lianxien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["e4930f6ef6cd4006b95b1cef204e7824"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["e4930f6ef6cd4006b95b1cef204e7824"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["bf732d60231e4141bb9c9b40cadfa609"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bf732d60231e4141bb9c9b40cadfa609",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"932de16c15734cca93dd2bd225b874b5",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":583.5,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"be9b7ce18b6c4ae48b1eb7df3305a4cd",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":696,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"e4930f6ef6cd4006b95b1cef204e7824",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":794,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"e76417c94a174d80856eab8bb1dc5fce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":2181},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950edb6981e7490f975038fc1b3ac7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":2181},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u94.png"}},
{
          "id":"cc60dc75af31419d8d1efa1e6def0773",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":194,
              "y":2316},
            "size":{
              "width":127,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d69bc3078ed343c69ce7a023bdd4f097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":194,
                  "y":2316},
                "size":{
                  "width":127,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56f7400011054923b49ee05b174513dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":2002},
            "size":{
              "width":118,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4989748a96ee47a78813187e9c4a67e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":2002},
                "size":{
                  "width":118,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u98.png"}},
{
          "id":"ec331ec66c7347a38ca734d0bf2bc830",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":666,
              "y":2132},
            "size":{
              "width":201,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747283d9dc0d481786c381a2745ff2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":666,
                  "y":2132},
                "size":{
                  "width":201,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7b3a1c46744429a842f8eafcf812369",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":445,
              "y":966},
            "size":{
              "width":135,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288c7c800e1a4b348484545e67ddf0d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":966},
                "size":{
                  "width":135,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c0b87e3295e4fa584b649449138c9eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6313E,
              "opacity":1},
            "location":{
              "x":461,
              "y":1782},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df33610ff43b4accb4819e799eb885d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6313E,
                  "opacity":1},
                "location":{
                  "x":461,
                  "y":1782},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0401bd9a69341d99f1af2d558d1cffc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":820},
            "size":{
              "width":201,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39fee1d32de74456a0a6a95d896b71c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":820},
                "size":{
                  "width":201,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u102.png"}},
{
          "id":"c702347bdc214d12bf029fdba67a3c2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":1444},
            "size":{
              "width":167,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704199ea4b92496f966dfde876dfffbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":1444},
                "size":{
                  "width":167,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u104.png"}},
{
          "id":"5a7fbeb9b54a43e5962cf90a82c0a8c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":446,
              "y":1389},
            "size":{
              "width":131,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b122291c256a4a41b2f5c9dcc7616468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":1389},
                "size":{
                  "width":131,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd3fd8deca434fc1a8d9e265300fd884",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":1424},
            "size":{
              "width":40,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/u110_line.png"}},
{
          "id":"48206e5c84704dc8b551ead58001fe5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":379,
              "y":1598},
            "size":{
              "width":270,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2306845dd7a049a9b25fbc04cd4a4554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":379,
                  "y":1598},
                "size":{
                  "width":270,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb0eb4cef6fa441b841dc67a9ae27cc3":{
      "scriptId":"u0"},
    "393e06cb22904212bc91faea014cc2c0":{
      "scriptId":"u1"},
    "e576bd898dd04563aca8518d6384603d":{
      "scriptId":"u2"},
    "37c74daa4b3d482cb005af3ceeb7288b":{
      "scriptId":"u3"},
    "2c6b9c8861924059bebe4e2b8bdccdb1":{
      "scriptId":"u4"},
    "59e322d3cf9d4130a2b881206bb29378":{
      "scriptId":"u5"},
    "9f4c9bcf679c47b1949617b425c5950f":{
      "scriptId":"u6"},
    "ef67ef7ebc444280bb56e41cb1038a82":{
      "scriptId":"u7"},
    "4b53ee0af5034dd7986729a1e43649b0":{
      "scriptId":"u8"},
    "2f8e3e1ef71e4a4cacde53d77ee94fb1":{
      "scriptId":"u9"},
    "20ba5152d12e4777a2a8c50feabb45b3":{
      "scriptId":"u10"},
    "1d4a7cd1c5124bc1a1151ba4b977aeeb":{
      "scriptId":"u11"},
    "3420862106944d12bcc3e87679f1d9d4":{
      "scriptId":"u12"},
    "321fab54de0d4458b968600fd2911b64":{
      "scriptId":"u13"},
    "bc4218edc9804759bab9f6b4c9b48805":{
      "scriptId":"u14"},
    "a0f939b075744e2f8cb1b4c6cb888415":{
      "scriptId":"u15"},
    "e793fe0fd49c4982971110bccb20d1f1":{
      "scriptId":"u16"},
    "b7d3f6c3e06648a18ad4d0eb8f923a09":{
      "scriptId":"u17"},
    "3cac348de07c4345b291ab15ad6a07af":{
      "scriptId":"u18"},
    "fa8b7376232c434cabc09d7d2cc8e343":{
      "scriptId":"u19"},
    "297738ec169d4295bd8b8a6293df732a":{
      "scriptId":"u20"},
    "e098d68bf6ca46548b47e9073da915f0":{
      "scriptId":"u21"},
    "efa51a4c33574e97af98ca0100d5e69e":{
      "scriptId":"u22"},
    "3e5b39694f3e4eff96eab448af197715":{
      "scriptId":"u23"},
    "1dbd9c74552a4de1a316f79f0e2a8f4a":{
      "scriptId":"u24"},
    "cdf834d3f0494567bf2318f77fbfb59b":{
      "scriptId":"u25"},
    "1e2ec4a0c59c476d9bef08ba46956d94":{
      "scriptId":"u26"},
    "7bd61b67113f42fbbb54644cc07fbf8f":{
      "scriptId":"u27"},
    "09df7b73ba074340a7d73dc938cab1ef":{
      "scriptId":"u28"},
    "7055122a2ff84bc8b397b15390f9ba1b":{
      "scriptId":"u29"},
    "b6fbcd9c46574a86aa08999de0c7738e":{
      "scriptId":"u30"},
    "da35dffaf2a845beb0c71e7f11c4ab46":{
      "scriptId":"u31"},
    "4cca77058d8f474ab49b3c489d294116":{
      "scriptId":"u32"},
    "bad58c1ee55045b98bef5bd5b49b0a1f":{
      "scriptId":"u33"},
    "13829491c8304045acf25957e864568c":{
      "scriptId":"u34"},
    "f246db1a02f240e5967994d7964e6c8c":{
      "scriptId":"u35"},
    "162148ee7877490ea99181d6a8f5503a":{
      "scriptId":"u36"},
    "b7ae945ed25b4b4b9bee6a9baa1d66e6":{
      "scriptId":"u37"},
    "9a63b55e5078464a8f91c7b07f1a76c3":{
      "scriptId":"u38"},
    "11df8e409980400a8546c665a9840e2a":{
      "scriptId":"u39"},
    "a90827473b3a43a3b8cf6bf4873a8e9f":{
      "scriptId":"u40"},
    "6669c043a1e347f3a1013b1a2160e02d":{
      "scriptId":"u41"},
    "726531201bd04d549fe372dbb855a3ee":{
      "scriptId":"u42"},
    "22d200b19e1b48ed9d6e5edeedf04508":{
      "scriptId":"u43"},
    "a934c7e518b44a459c6c5e87845d3c3f":{
      "scriptId":"u44"},
    "14d294c4abbe465599b3997e160f8a81":{
      "scriptId":"u45"},
    "384ec736baf1450383a86727fa3107e3":{
      "scriptId":"u46"},
    "9e611dec862d41aa842f569f98ff7e8f":{
      "scriptId":"u47"},
    "4df2e9b6539e47be9445591802ced6e3":{
      "scriptId":"u48"},
    "8b4e069ae302451f9b95bdfbd8718964":{
      "scriptId":"u49"},
    "f884585810c74401a67af4e05a79b091":{
      "scriptId":"u50"},
    "935cebdad52942b5ade580d6fd329a31":{
      "scriptId":"u51"},
    "c0b208a463884f13bcd93f3acea0d1d7":{
      "scriptId":"u52"},
    "6fb4903b3d0049dca87d20ee3dd6683d":{
      "scriptId":"u53"},
    "7b82a1e6d4e248f184a8c332ca1113db":{
      "scriptId":"u54"},
    "a4a7feddeeb44e9693d4cdc7159b84d7":{
      "scriptId":"u55"},
    "7e7477ee562c4840b68585c3d91e6559":{
      "scriptId":"u56"},
    "98540b4feb3144609ab71f665b7ed899":{
      "scriptId":"u57"},
    "b6e7faac5b99490ebd05c4fb3e6d7a7f":{
      "scriptId":"u58"},
    "9342a4c624684ee5b4a3d30de2922aa6":{
      "scriptId":"u59"},
    "3a5475f03be7475daf2d1cd9cf6f1cb5":{
      "scriptId":"u60"},
    "95c09805724546ddb398267eee0a64c8":{
      "scriptId":"u61"},
    "5b480ac491fa405498ab472cf887e7df":{
      "scriptId":"u62"},
    "a5ade7b13fa34059bec55ffcbf84eeb3":{
      "scriptId":"u63"},
    "277eba61411a46a196878da32013b4e8":{
      "scriptId":"u64"},
    "6065835e30cf48e2a006cd5570d825f1":{
      "scriptId":"u65"},
    "ab9497544dbb4e17b07e0e461e200cf0":{
      "scriptId":"u66"},
    "5632cc953b3d42faad569fae4af409b1":{
      "scriptId":"u67"},
    "4c45b794ce004741a5471afd972edd84":{
      "scriptId":"u68"},
    "f22db71cc8994f239ad172c1c9d0cefb":{
      "scriptId":"u69"},
    "58676220c8d74c9a9620118578205313":{
      "scriptId":"u70"},
    "e0204de864a7450396b123d05c954d7b":{
      "scriptId":"u71"},
    "e9095ddf28a44fd7980ca4978a6dbac9":{
      "scriptId":"u72"},
    "49ca27a0ba93447ba0c48845a34b6c93":{
      "scriptId":"u73"},
    "e1b03a7d62e44494a0d650eba7096426":{
      "scriptId":"u74"},
    "5589bd53c68042d487b6a4dfa3bd6160":{
      "scriptId":"u75"},
    "eac53b74024c41269ca3ce48c09ad5bd":{
      "scriptId":"u76"},
    "2dca05cdc02f49359740835cba85e5ca":{
      "scriptId":"u77"},
    "dca10ec8b70f4ebe8338c4c150c05b36":{
      "scriptId":"u78"},
    "f5403561c3a14e8781a475d9e930a56f":{
      "scriptId":"u79"},
    "3c9ee911944a4ad4aa741b593fb80ea4":{
      "scriptId":"u80"},
    "6fac24f7331c44f0a6c44be25a5023a4":{
      "scriptId":"u81"},
    "8df3b9e3e2f145bf9b384b1b036fb39c":{
      "scriptId":"u82"},
    "ba1a364badc64c6fb2db72a0d4ee3f3a":{
      "scriptId":"u83"},
    "9e0070937b6e4d9fbe549b0c781fb8fa":{
      "scriptId":"u84"},
    "817a1ae3cbea43bba77ddf0cd6ef03bb":{
      "scriptId":"u85"},
    "bf732d60231e4141bb9c9b40cadfa609":{
      "scriptId":"u86"},
    "932de16c15734cca93dd2bd225b874b5":{
      "scriptId":"u87"},
    "be9b7ce18b6c4ae48b1eb7df3305a4cd":{
      "scriptId":"u88"},
    "e4930f6ef6cd4006b95b1cef204e7824":{
      "scriptId":"u89"},
    "e76417c94a174d80856eab8bb1dc5fce":{
      "scriptId":"u90"},
    "950edb6981e7490f975038fc1b3ac7e3":{
      "scriptId":"u91"},
    "cc60dc75af31419d8d1efa1e6def0773":{
      "scriptId":"u92"},
    "d69bc3078ed343c69ce7a023bdd4f097":{
      "scriptId":"u93"},
    "56f7400011054923b49ee05b174513dc":{
      "scriptId":"u94"},
    "4989748a96ee47a78813187e9c4a67e6":{
      "scriptId":"u95"},
    "ec331ec66c7347a38ca734d0bf2bc830":{
      "scriptId":"u96"},
    "747283d9dc0d481786c381a2745ff2b7":{
      "scriptId":"u97"},
    "c7b3a1c46744429a842f8eafcf812369":{
      "scriptId":"u98"},
    "288c7c800e1a4b348484545e67ddf0d6":{
      "scriptId":"u99"},
    "9c0b87e3295e4fa584b649449138c9eb":{
      "scriptId":"u100"},
    "df33610ff43b4accb4819e799eb885d0":{
      "scriptId":"u101"},
    "b0401bd9a69341d99f1af2d558d1cffc":{
      "scriptId":"u102"},
    "39fee1d32de74456a0a6a95d896b71c1":{
      "scriptId":"u103"},
    "c702347bdc214d12bf029fdba67a3c2d":{
      "scriptId":"u104"},
    "704199ea4b92496f966dfde876dfffbe":{
      "scriptId":"u105"},
    "5a7fbeb9b54a43e5962cf90a82c0a8c7":{
      "scriptId":"u106"},
    "b122291c256a4a41b2f5c9dcc7616468":{
      "scriptId":"u107"},
    "cd3fd8deca434fc1a8d9e265300fd884":{
      "scriptId":"u108"},
    "48206e5c84704dc8b551ead58001fe5e":{
      "scriptId":"u109"},
    "2306845dd7a049a9b25fbc04cd4a4554":{
      "scriptId":"u110"}}});