$axure.loadCurrentPage({
  "url":"lianxien.html",
  "generationDate":new Date(1465358670431.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"346ea7d7ef2b4427807187cc1e4d89b3",
    "type":"Axure:Page",
    "name":"lianxiEN",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34f397f5a2e6414a8e6726d9c647048e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":213}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f1caadc65746b2ac5c7a79f65c53ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":213}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lianxi/u0.jpg"}},
{
          "id":"5af740c2caaf4b26813c3c5df534f04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":857,
              "y":21},
            "size":{
              "width":58,
              "height":22},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f73dd918f3e94a8ca64f95c5d0c430b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":857,
                  "y":21},
                "size":{
                  "width":58,
                  "height":22},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u74.png"}},
{
          "id":"3941a01ebce84080b18b0db47c5a4e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":891,
              "y":22},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bfed680208b4365aba2d88395d0625b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":891,
                  "y":22},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u76.png"}},
{
          "id":"65908f6f8865400094463881e16bf575",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":864,
              "y":24},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c083a81ed9994e52bc27dfdf4edf0eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":864,
                  "y":24},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 lianxi",
                      "target":{
                        "targetType":"page",
                        "url":"lianxi.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c956e626dd34f9fad516f49d598d03f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":892,
              "y":24},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f678fd26d5426daa7fdc5862494753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":24},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1d67fbaad5f4b5a849e8cf4f4b5e90e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":115},
            "size":{
              "width":602,
              "height":484},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":15,
              "color":{
                "r":214,
                "g":50,
                "b":63,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e39d3dad9444c87bad62f1dd7e7bc0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":115},
                "size":{
                  "width":602,
                  "height":484},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":15,
                  "color":{
                    "r":214,
                    "g":50,
                    "b":63,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lianxi/u22.png"}},
{
          "id":"994a30f51271467da3ac7883dfc7d636",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":319,
              "y":136},
            "size":{
              "width":219,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f232d0060e8b442d886c25de22b7d1bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":319,
                  "y":136},
                "size":{
                  "width":219,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16e793d005c1411f872567134a36ba78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":348,
              "y":176},
            "size":{
              "width":309,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d39c154afb684e568a7eab39eaa8493f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":348,
                  "y":176},
                "size":{
                  "width":309,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98e2e672fc4042d6961ae83f1addd65e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":347,
              "y":203},
            "size":{
              "width":327,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381a4f0daa824e1da65309c69384deec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":347,
                  "y":203},
                "size":{
                  "width":327,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ce1d8428ebf4e6b841e7197356bcf99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":319,
              "y":266},
            "size":{
              "width":111,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b81d25c3fa4d29aa8ef40043889bd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":319,
                  "y":266},
                "size":{
                  "width":111,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e6fb8285b754a8196297a63055ac9f6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":319,
              "y":310},
            "size":{
              "width":400,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"Your nickname"},
{
          "id":"fa365adf513e4d3cbc31b2c45917a5f4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":319,
              "y":345},
            "size":{
              "width":400,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"Your contact information"},
{
          "id":"2e8e39e0cb544e3db18afbeeebeb60d4",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":319,
              "y":400},
            "size":{
              "width":400,
              "height":130}},
          "adaptiveStyles":{
},
          "placeholderText":"your message"},
{
          "id":"c1fe0b096b6c49a1adc56a605693840d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFC96569},
            "location":{
              "x":474,
              "y":550},
            "size":{
              "width":99,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ab2f315d1cd42c6962b916bcabc2863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":3,
                      "offsetY":3,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC96569},
                "location":{
                  "x":474,
                  "y":550},
                "size":{
                  "width":99,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lianxi/u35.png",
            "mouseDown~":"images/lianxi/u35_mouseDown.png"}},
{
          "id":"92ec3e4ed1d4402cb318c02e3f1843b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7bf0bc9234e468d8317d8f2fc4f416e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":620},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u68.png"}},
{
          "id":"489456162f734d68b1a81187012a9f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5412e809495242fa813d69a7f88f52b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u72.png"}},
{
          "id":"02db4df99b4142699e89a43aa0724392",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":314,
              "y":662},
            "size":{
              "width":398,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2abfcd466a454dfaa14968bdb99924df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":314,
                  "y":662},
                "size":{
                  "width":398,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b7ab980401841e49677958e3ab468eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":476,
              "y":24},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f9c6f7b7284647a1fd503db5bef8d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":476,
                  "y":24},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 indexEN",
                      "target":{
                        "targetType":"page",
                        "url":"indexen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["7c68933d18e944ffb27b9b9ef8da3c4f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["7c68933d18e944ffb27b9b9ef8da3c4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b686483bcb5046cdae0f8482451b8f0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":540,
              "y":24},
            "size":{
              "width":112,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03ca8f884ee41c3859e3e7c76e26b4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":540,
                  "y":24},
                "size":{
                  "width":112,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwuEN",
                      "target":{
                        "targetType":"page",
                        "url":"fuwuen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["4635aa1ca8ab4e8886fe3fe9205dd66f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["4635aa1ca8ab4e8886fe3fe9205dd66f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c96541c28aa94cd0b3207f223f5e9017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":650,
              "y":24},
            "size":{
              "width":123,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2eb359564b54203a3ce5af69c124060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":650,
                  "y":24},
                "size":{
                  "width":123,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuanduiEN",
                      "target":{
                        "targetType":"page",
                        "url":"tuanduien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["a4010016d1324e929b5815f888f14308"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["a4010016d1324e929b5815f888f14308"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["a680806042ed440da3ebcfc7a23f93f3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9a9f441a12fe44cfb70cb87df7a5bf2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":773,
              "y":24},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bca8ef45c014ef1857a87437525b751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":773,
                  "y":24},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 lianxiEN",
                      "target":{
                        "targetType":"page",
                        "url":"lianxien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7c68933d18e944ffb27b9b9ef8da3c4f",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":489,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"4635aa1ca8ab4e8886fe3fe9205dd66f",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":584,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"a4010016d1324e929b5815f888f14308",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":696,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"a680806042ed440da3ebcfc7a23f93f3",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "34f397f5a2e6414a8e6726d9c647048e":{
      "scriptId":"u0"},
    "73f1caadc65746b2ac5c7a79f65c53ed":{
      "scriptId":"u1"},
    "5af740c2caaf4b26813c3c5df534f04e":{
      "scriptId":"u2"},
    "f73dd918f3e94a8ca64f95c5d0c430b1":{
      "scriptId":"u3"},
    "3941a01ebce84080b18b0db47c5a4e08":{
      "scriptId":"u4"},
    "3bfed680208b4365aba2d88395d0625b":{
      "scriptId":"u5"},
    "65908f6f8865400094463881e16bf575":{
      "scriptId":"u6"},
    "c083a81ed9994e52bc27dfdf4edf0eb3":{
      "scriptId":"u7"},
    "1c956e626dd34f9fad516f49d598d03f":{
      "scriptId":"u8"},
    "c7f678fd26d5426daa7fdc5862494753":{
      "scriptId":"u9"},
    "e1d67fbaad5f4b5a849e8cf4f4b5e90e":{
      "scriptId":"u10"},
    "1e39d3dad9444c87bad62f1dd7e7bc0f":{
      "scriptId":"u11"},
    "994a30f51271467da3ac7883dfc7d636":{
      "scriptId":"u12"},
    "f232d0060e8b442d886c25de22b7d1bb":{
      "scriptId":"u13"},
    "16e793d005c1411f872567134a36ba78":{
      "scriptId":"u14"},
    "d39c154afb684e568a7eab39eaa8493f":{
      "scriptId":"u15"},
    "98e2e672fc4042d6961ae83f1addd65e":{
      "scriptId":"u16"},
    "381a4f0daa824e1da65309c69384deec":{
      "scriptId":"u17"},
    "8ce1d8428ebf4e6b841e7197356bcf99":{
      "scriptId":"u18"},
    "23b81d25c3fa4d29aa8ef40043889bd0":{
      "scriptId":"u19"},
    "4e6fb8285b754a8196297a63055ac9f6":{
      "scriptId":"u20"},
    "fa365adf513e4d3cbc31b2c45917a5f4":{
      "scriptId":"u21"},
    "2e8e39e0cb544e3db18afbeeebeb60d4":{
      "scriptId":"u22"},
    "c1fe0b096b6c49a1adc56a605693840d":{
      "scriptId":"u23"},
    "6ab2f315d1cd42c6962b916bcabc2863":{
      "scriptId":"u24"},
    "92ec3e4ed1d4402cb318c02e3f1843b7":{
      "scriptId":"u25"},
    "e7bf0bc9234e468d8317d8f2fc4f416e":{
      "scriptId":"u26"},
    "489456162f734d68b1a81187012a9f4f":{
      "scriptId":"u27"},
    "5412e809495242fa813d69a7f88f52b0":{
      "scriptId":"u28"},
    "02db4df99b4142699e89a43aa0724392":{
      "scriptId":"u29"},
    "2abfcd466a454dfaa14968bdb99924df":{
      "scriptId":"u30"},
    "0b7ab980401841e49677958e3ab468eb":{
      "scriptId":"u31"},
    "43f9c6f7b7284647a1fd503db5bef8d0":{
      "scriptId":"u32"},
    "b686483bcb5046cdae0f8482451b8f0d":{
      "scriptId":"u33"},
    "c03ca8f884ee41c3859e3e7c76e26b4d":{
      "scriptId":"u34"},
    "c96541c28aa94cd0b3207f223f5e9017":{
      "scriptId":"u35"},
    "c2eb359564b54203a3ce5af69c124060":{
      "scriptId":"u36"},
    "9a9f441a12fe44cfb70cb87df7a5bf2f":{
      "scriptId":"u37"},
    "0bca8ef45c014ef1857a87437525b751":{
      "scriptId":"u38"},
    "7c68933d18e944ffb27b9b9ef8da3c4f":{
      "scriptId":"u39"},
    "4635aa1ca8ab4e8886fe3fe9205dd66f":{
      "scriptId":"u40"},
    "a4010016d1324e929b5815f888f14308":{
      "scriptId":"u41"},
    "a680806042ed440da3ebcfc7a23f93f3":{
      "scriptId":"u42"}}});