$axure.loadCurrentPage({
  "url":"fuwu.html",
  "generationDate":new Date(1465358669242.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f27ffa13146e4ab7a4711d93dc07c0d7",
    "type":"Axure:Page",
    "name":"fuwu",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c84435a126b1410d8b07879765429849",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":431},
            "size":{
              "width":179,
              "height":299},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba35fd505be437bb86ea83c899729b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":431},
                "size":{
                  "width":179,
                  "height":299},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u0.png"}},
{
          "id":"325fc42cfa46478489208ef4c5ec4f7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":431},
            "size":{
              "width":179,
              "height":299},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4ded4cb3874f90b04f50f0dcf6d0d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":431},
                "size":{
                  "width":179,
                  "height":299},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u0.png"}},
{
          "id":"773980cf7b7a4b9ea11fa7a37fb67d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":431},
            "size":{
              "width":179,
              "height":299},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e56dbd022e64788bd3f2a26a8c47ff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":431},
                "size":{
                  "width":179,
                  "height":299},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u0.png"}},
{
          "id":"336bc9194340409783733ddd0270b396",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "size":{
              "width":1024,
              "height":213}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a7f427870f4639887bb0492986b5eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "size":{
                  "width":1024,
                  "height":213}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u6.jpg"}},
{
          "id":"8f8b4f4d62054548bd37e61b5d819df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":115},
            "size":{
              "width":750,
              "height":255},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":4,
              "blurRadius":8,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bdb4e9760d94df491c162a53ce01253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":115},
                "size":{
                  "width":750,
                  "height":255},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":4,
                  "blurRadius":8,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u8.png"}},
{
          "id":"006e591ae451424aad366bbbe1517d1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6325F,
              "opacity":1},
            "location":{
              "x":200,
              "y":150},
            "size":{
              "width":101,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f85b20a1254d92876fa8899494319e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6325F,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":101,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43b5b2ff3cd04337b9c3c2a0bc08aba9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":200,
              "y":222},
            "size":{
              "width":450,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"577738e1239f42d3baf1f771b8a994b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":222},
                "size":{
                  "width":450,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5dd8dee750f491a9903cee3c0f84787",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":712,
              "y":165.5},
            "size":{
              "width":130,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c760f8295d46cb922507e00ce9dd19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":712,
                  "y":165.5},
                "size":{
                  "width":130,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u14.png"}},
{
          "id":"6c9bdc1dc5af41bea22bff17235e6ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA,
              "opacity":1},
            "location":{
              "x":200,
              "y":176},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b9d07e7f954a128074c036c9809111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":176},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5692854f33274047a95061526269cb3b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":344},
            "size":{
              "width":50,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":8,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540f0c52d278448c8ee7162d1e3bfc19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":344},
                "size":{
                  "width":50,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":8,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u18.png"}},
{
          "id":"7881f81a2c394c3aa59974bb07b2ba84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":431},
            "size":{
              "width":179,
              "height":299},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a743db6ed3e2447199c7cc99dca5819a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":431},
                "size":{
                  "width":179,
                  "height":299},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u0.png"}},
{
          "id":"d5c41fcc7f1840d3be07a1606ba696f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":431},
            "size":{
              "width":179,
              "height":48},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc412507e323477ab28eaf718d9ca18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":431},
                "size":{
                  "width":179,
                  "height":48},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u22.png"}},
{
          "id":"e2d5d129c8f64cd4a3d86017cab217ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":490},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc8fd02fdff414591aefa89467ddbe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":490},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u24.png"}},
{
          "id":"add43083a7e74c3b9271ee27aaf0e8b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":490},
            "size":{
              "width":69,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d793dd7bdc1c49bf914b018685b6faf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":490},
                "size":{
                  "width":69,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c18e18fa1f934ab593e679b732af8dfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":166,
              "y":515},
            "size":{
              "width":92,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46ba71bde65745a3b7de7b8aa393019b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":515},
                "size":{
                  "width":92,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aac44767aff34d2bbc0443a399447ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD6313E},
            "location":{
              "x":165.5,
              "y":544},
            "size":{
              "width":124,
              "height":27},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1cef790e11140ac87b118cb01f1bc19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6313E},
                "location":{
                  "x":165.5,
                  "y":544},
                "size":{
                  "width":124,
                  "height":27},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 http://www.zhuaizhijia.com",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.zhuaizhijia.com",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/fuwu/u30.png"}},
{
          "id":"5d76b271faff45dfb952f8ef553d381c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":600},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b81c20bb7643459a8204564ee1b55a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":600},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u32.png"}},
{
          "id":"eeb7228dcba64cd99f36ef425878fb02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":601},
            "size":{
              "width":68,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d5f66f3df64eafb1fc27f550aac917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":601},
                "size":{
                  "width":68,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3cdeb135d5d4fcb9fbe1d9e19dbdeef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":158,
              "y":626},
            "size":{
              "width":144,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae74e09a051b4940921a0c306619c8d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":626},
                "size":{
                  "width":144,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09319ae308c84ce28e369becff4df031",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":581},
            "size":{
              "width":144,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fuwu/u38_line.png"}},
{
          "id":"228d44785f7e4b8b9c8557ec447330ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":391.5,
              "y":511},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e9427feb87446fa829e81714ee5f39a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391.5,
                  "y":511},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u39.png"}},
{
          "id":"a549aa91b5e94b2290a69b12ee63de75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":518},
            "size":{
              "width":80,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb750028131403a8f58f6cc4abe2467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":518},
                "size":{
                  "width":80,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u41.png"}},
{
          "id":"b51ef45c6a3b43379099f9356e13a30c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":516},
            "size":{
              "width":80,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2230800e2f5845c09f8b9a64ef1b2381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":516},
                "size":{
                  "width":80,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u43.png"}},
{
          "id":"e2a6584de6154640a5ae0391050a7dc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":359,
              "y":613},
            "size":{
              "width":136,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94e0901a4eb84eb98626282f1a911a2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":613},
                "size":{
                  "width":136,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e589a6eeb9f4ffe8305c791d047c32d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":556,
              "y":613},
            "size":{
              "width":136,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb0d7a38bc0a4e97a29559b0c897c308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":613},
                "size":{
                  "width":136,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aad0c3ab8aec45eb9f01c15c6ad7619a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":752,
              "y":613},
            "size":{
              "width":136,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a49709a86fa4fe1ad1eca4fe20cbcbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":752,
                  "y":613},
                "size":{
                  "width":136,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab3fb698c27542d181a7b881c59ded75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":179,
              "y":448},
            "size":{
              "width":106,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d55a5ae231b946f89bd2106b04048b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":179,
                  "y":448},
                "size":{
                  "width":106,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5985556b264442468e06a89d83be3328",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":431},
            "size":{
              "width":179,
              "height":48},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94621766f4c24d12a1cf71706a3ad5b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":431},
                "size":{
                  "width":179,
                  "height":48},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u22.png"}},
{
          "id":"15ca6c8e37be4917806f846a3908d665",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":368,
              "y":448},
            "size":{
              "width":121,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad0462229b8148a99cb80661613c8cb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":368,
                  "y":448},
                "size":{
                  "width":121,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e57ff67e31b4eaa96cd0bf7a3d602a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":431},
            "size":{
              "width":179,
              "height":48},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2406315639bf4489a76e469044e7ae21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":431},
                "size":{
                  "width":179,
                  "height":48},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u22.png"}},
{
          "id":"d69e812e2d204dedb4c3cf31ecb1cc7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":578,
              "y":448},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084449bf04a54457897ec68ea3988f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":578,
                  "y":448},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0281f9bad2d44499f61c019accdcdf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":431},
            "size":{
              "width":179,
              "height":48},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":10,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474630330638494c86d7b465e8193893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":431},
                "size":{
                  "width":179,
                  "height":48},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":10,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fuwu/u22.png"}},
{
          "id":"6731b5740b074626814eca16957826b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":782,
              "y":448},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4888ab2d0494b9da86b30e7a861caa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":782,
                  "y":448},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6173e42180db4ca5aa19a3ff675a6acb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":760},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca00268c20840af84d9ba9e148cc95d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":760},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u68.png"}},
{
          "id":"bd7714fb8dc844a8be9ef392d1db34ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":860},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c232a11400f94bd3ab4f983e3d2132dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":860},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u72.png"}},
{
          "id":"43a3315937ef4cc6ad524523364a73d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":498,
              "y":24},
            "size":{
              "width":79,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f254bde01d74800b378862fd3e61637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":498,
                  "y":24},
                "size":{
                  "width":79,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["bc8c18a44d674f7d82338e6da1d25782"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["bc8c18a44d674f7d82338e6da1d25782"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"878466683dff4e24b343199460d4553a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":577,
              "y":24},
            "size":{
              "width":80,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe3b27b2fb2f42a0ae7aa5b44159686b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":577,
                  "y":24},
                "size":{
                  "width":80,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwu",
                      "target":{
                        "targetType":"page",
                        "url":"fuwu.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"e4f106de28654af38472e62b6e6cae87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":656,
              "y":24},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bae07f04334b49969a0c176bf47800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":656,
                  "y":24},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuandui",
                      "target":{
                        "targetType":"page",
                        "url":"tuandui.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["422fde215d0b4f0292f541312a222a4d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["422fde215d0b4f0292f541312a222a4d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bc8c18a44d674f7d82338e6da1d25782",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":508,
              "y":43},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fuwu/1_u75_line.png"}},
{
          "id":"287f9d32d1a841f9888fd74f66946d15",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":43},
            "size":{
              "width":28,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fuwu/2_u76_line.png"}},
{
          "id":"422fde215d0b4f0292f541312a222a4d",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":678,
              "y":43},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fuwu/1_u75_line.png"}},
{
          "id":"0bb18bb20a5d4172b311ad20bcae13c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":843,
              "y":25},
            "size":{
              "width":58,
              "height":22},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eb027ecec11456fae5949f3a1cbf70b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":843,
                  "y":25},
                "size":{
                  "width":58,
                  "height":22},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u74.png"}},
{
          "id":"7779a894d33c426a992a1281ba392b82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":846,
              "y":26},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf67f9abe85648e9ae4f1837f8ff6c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":846,
                  "y":26},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u76.png"}},
{
          "id":"29c22e7f7cec4570aff63de3bc6960d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":850,
              "y":28},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd06103df5c450390c7c1d01d153453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":850,
                  "y":28},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39c43ea485814c5a9bd019934d0b7ab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":874,
              "y":28},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58086112bde64dc4ae2419845a98e3aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":28},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwuEN",
                      "target":{
                        "targetType":"page",
                        "url":"fuwuen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeb7afac09e343c7bfa86f4538b539cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":745,
              "y":24},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea47464668442a3b535ab17cf1a16bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":745,
                  "y":24},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 lianxi",
                      "target":{
                        "targetType":"page",
                        "url":"lianxi.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["13b1eecbdd8c4a71baca95d8145ff4a5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["13b1eecbdd8c4a71baca95d8145ff4a5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["287f9d32d1a841f9888fd74f66946d15"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"13b1eecbdd8c4a71baca95d8145ff4a5",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":758,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fuwu/1_u75_line.png"}},
{
          "id":"d3e60a2b0ba44fc1b85bdb535eb699ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":332,
              "y":802},
            "size":{
              "width":398,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d5c82ee9e5141e791ffd8a9d350095a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":332,
                  "y":802},
                "size":{
                  "width":398,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c84435a126b1410d8b07879765429849":{
      "scriptId":"u0"},
    "1ba35fd505be437bb86ea83c899729b4":{
      "scriptId":"u1"},
    "325fc42cfa46478489208ef4c5ec4f7b":{
      "scriptId":"u2"},
    "fd4ded4cb3874f90b04f50f0dcf6d0d5":{
      "scriptId":"u3"},
    "773980cf7b7a4b9ea11fa7a37fb67d5f":{
      "scriptId":"u4"},
    "6e56dbd022e64788bd3f2a26a8c47ff7":{
      "scriptId":"u5"},
    "336bc9194340409783733ddd0270b396":{
      "scriptId":"u6"},
    "65a7f427870f4639887bb0492986b5eb":{
      "scriptId":"u7"},
    "8f8b4f4d62054548bd37e61b5d819df5":{
      "scriptId":"u8"},
    "7bdb4e9760d94df491c162a53ce01253":{
      "scriptId":"u9"},
    "006e591ae451424aad366bbbe1517d1b":{
      "scriptId":"u10"},
    "f1f85b20a1254d92876fa8899494319e":{
      "scriptId":"u11"},
    "43b5b2ff3cd04337b9c3c2a0bc08aba9":{
      "scriptId":"u12"},
    "577738e1239f42d3baf1f771b8a994b6":{
      "scriptId":"u13"},
    "d5dd8dee750f491a9903cee3c0f84787":{
      "scriptId":"u14"},
    "f3c760f8295d46cb922507e00ce9dd19":{
      "scriptId":"u15"},
    "6c9bdc1dc5af41bea22bff17235e6ab1":{
      "scriptId":"u16"},
    "c4b9d07e7f954a128074c036c9809111":{
      "scriptId":"u17"},
    "5692854f33274047a95061526269cb3b":{
      "scriptId":"u18"},
    "540f0c52d278448c8ee7162d1e3bfc19":{
      "scriptId":"u19"},
    "7881f81a2c394c3aa59974bb07b2ba84":{
      "scriptId":"u20"},
    "a743db6ed3e2447199c7cc99dca5819a":{
      "scriptId":"u21"},
    "d5c41fcc7f1840d3be07a1606ba696f7":{
      "scriptId":"u22"},
    "bc412507e323477ab28eaf718d9ca18d":{
      "scriptId":"u23"},
    "e2d5d129c8f64cd4a3d86017cab217ce":{
      "scriptId":"u24"},
    "bbc8fd02fdff414591aefa89467ddbe7":{
      "scriptId":"u25"},
    "add43083a7e74c3b9271ee27aaf0e8b5":{
      "scriptId":"u26"},
    "d793dd7bdc1c49bf914b018685b6faf7":{
      "scriptId":"u27"},
    "c18e18fa1f934ab593e679b732af8dfa":{
      "scriptId":"u28"},
    "46ba71bde65745a3b7de7b8aa393019b":{
      "scriptId":"u29"},
    "aac44767aff34d2bbc0443a399447ec4":{
      "scriptId":"u30"},
    "c1cef790e11140ac87b118cb01f1bc19":{
      "scriptId":"u31"},
    "5d76b271faff45dfb952f8ef553d381c":{
      "scriptId":"u32"},
    "12b81c20bb7643459a8204564ee1b55a":{
      "scriptId":"u33"},
    "eeb7228dcba64cd99f36ef425878fb02":{
      "scriptId":"u34"},
    "65d5f66f3df64eafb1fc27f550aac917":{
      "scriptId":"u35"},
    "c3cdeb135d5d4fcb9fbe1d9e19dbdeef":{
      "scriptId":"u36"},
    "ae74e09a051b4940921a0c306619c8d3":{
      "scriptId":"u37"},
    "09319ae308c84ce28e369becff4df031":{
      "scriptId":"u38"},
    "228d44785f7e4b8b9c8557ec447330ab":{
      "scriptId":"u39"},
    "9e9427feb87446fa829e81714ee5f39a":{
      "scriptId":"u40"},
    "a549aa91b5e94b2290a69b12ee63de75":{
      "scriptId":"u41"},
    "4cb750028131403a8f58f6cc4abe2467":{
      "scriptId":"u42"},
    "b51ef45c6a3b43379099f9356e13a30c":{
      "scriptId":"u43"},
    "2230800e2f5845c09f8b9a64ef1b2381":{
      "scriptId":"u44"},
    "e2a6584de6154640a5ae0391050a7dc1":{
      "scriptId":"u45"},
    "94e0901a4eb84eb98626282f1a911a2a":{
      "scriptId":"u46"},
    "7e589a6eeb9f4ffe8305c791d047c32d":{
      "scriptId":"u47"},
    "fb0d7a38bc0a4e97a29559b0c897c308":{
      "scriptId":"u48"},
    "aad0c3ab8aec45eb9f01c15c6ad7619a":{
      "scriptId":"u49"},
    "9a49709a86fa4fe1ad1eca4fe20cbcbc":{
      "scriptId":"u50"},
    "ab3fb698c27542d181a7b881c59ded75":{
      "scriptId":"u51"},
    "d55a5ae231b946f89bd2106b04048b32":{
      "scriptId":"u52"},
    "5985556b264442468e06a89d83be3328":{
      "scriptId":"u53"},
    "94621766f4c24d12a1cf71706a3ad5b3":{
      "scriptId":"u54"},
    "15ca6c8e37be4917806f846a3908d665":{
      "scriptId":"u55"},
    "ad0462229b8148a99cb80661613c8cb9":{
      "scriptId":"u56"},
    "5e57ff67e31b4eaa96cd0bf7a3d602a7":{
      "scriptId":"u57"},
    "2406315639bf4489a76e469044e7ae21":{
      "scriptId":"u58"},
    "d69e812e2d204dedb4c3cf31ecb1cc7b":{
      "scriptId":"u59"},
    "084449bf04a54457897ec68ea3988f7d":{
      "scriptId":"u60"},
    "e0281f9bad2d44499f61c019accdcdf5":{
      "scriptId":"u61"},
    "474630330638494c86d7b465e8193893":{
      "scriptId":"u62"},
    "6731b5740b074626814eca16957826b1":{
      "scriptId":"u63"},
    "f4888ab2d0494b9da86b30e7a861caa2":{
      "scriptId":"u64"},
    "6173e42180db4ca5aa19a3ff675a6acb":{
      "scriptId":"u65"},
    "7ca00268c20840af84d9ba9e148cc95d":{
      "scriptId":"u66"},
    "bd7714fb8dc844a8be9ef392d1db34ec":{
      "scriptId":"u67"},
    "c232a11400f94bd3ab4f983e3d2132dd":{
      "scriptId":"u68"},
    "43a3315937ef4cc6ad524523364a73d2":{
      "scriptId":"u69"},
    "1f254bde01d74800b378862fd3e61637":{
      "scriptId":"u70"},
    "878466683dff4e24b343199460d4553a":{
      "scriptId":"u71"},
    "fe3b27b2fb2f42a0ae7aa5b44159686b":{
      "scriptId":"u72"},
    "e4f106de28654af38472e62b6e6cae87":{
      "scriptId":"u73"},
    "95bae07f04334b49969a0c176bf47800":{
      "scriptId":"u74"},
    "bc8c18a44d674f7d82338e6da1d25782":{
      "scriptId":"u75"},
    "287f9d32d1a841f9888fd74f66946d15":{
      "scriptId":"u76"},
    "422fde215d0b4f0292f541312a222a4d":{
      "scriptId":"u77"},
    "0bb18bb20a5d4172b311ad20bcae13c2":{
      "scriptId":"u78"},
    "5eb027ecec11456fae5949f3a1cbf70b":{
      "scriptId":"u79"},
    "7779a894d33c426a992a1281ba392b82":{
      "scriptId":"u80"},
    "bf67f9abe85648e9ae4f1837f8ff6c66":{
      "scriptId":"u81"},
    "29c22e7f7cec4570aff63de3bc6960d6":{
      "scriptId":"u82"},
    "5cd06103df5c450390c7c1d01d153453":{
      "scriptId":"u83"},
    "39c43ea485814c5a9bd019934d0b7ab5":{
      "scriptId":"u84"},
    "58086112bde64dc4ae2419845a98e3aa":{
      "scriptId":"u85"},
    "aeb7afac09e343c7bfa86f4538b539cd":{
      "scriptId":"u86"},
    "9ea47464668442a3b535ab17cf1a16bd":{
      "scriptId":"u87"},
    "13b1eecbdd8c4a71baca95d8145ff4a5":{
      "scriptId":"u88"},
    "d3e60a2b0ba44fc1b85bdb535eb699ee":{
      "scriptId":"u89"},
    "0d5c82ee9e5141e791ffd8a9d350095a":{
      "scriptId":"u90"}}});