$axure.loadCurrentPage({
  "url":"tuandui.html",
  "generationDate":new Date(1465358669543.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aad910a554714bd6ac122d5812863992",
    "type":"Axure:Page",
    "name":"tuandui",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1832d8bace4a4fc3aa3b071a2b2321e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":1176},
            "size":{
              "width":420,
              "height":274},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f819bbe2d0c43978918025840e4f24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":1176},
                "size":{
                  "width":420,
                  "height":274},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u0.png"}},
{
          "id":"8ed3ca659b0d475fb031622ef2403c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":530,
              "y":893},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172027704ab74c2ab1787cff59f8fd63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":530,
                  "y":893},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"0eacfd3b90a14cae987498e225faca25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":890},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf12027bc4a04343915b1d2fe39ece17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":890},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"d421171a451f47ca9d4470248c495d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":530,
              "y":600},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c03c2c140f48ffa9d71d1ca8d9e6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":530,
                  "y":600},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"12f086fa2bc54f0cbec9a5ab0919ea52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":600},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27313ce8de1f443d9751fe988ea51306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":600},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"19672da44e87406f8c4f0c150929ef99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":213}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2219cdf541fc4955b92cec284e82a433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":213}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u10.jpg"}},
{
          "id":"9ac174f0738747efb733ea840fb10c0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":498,
              "y":24},
            "size":{
              "width":79,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b9d3e150cc4d8eac164e38cfc4f4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":498,
                  "y":24},
                "size":{
                  "width":79,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["99dc72b37fe447cbb2731cf02bdaab46"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["99dc72b37fe447cbb2731cf02bdaab46"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ec3118200757408dbfbb967a741d8b2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":577,
              "y":24},
            "size":{
              "width":71,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183aba501981460a98bb0ddc109ce063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":577,
                  "y":24},
                "size":{
                  "width":71,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwu",
                      "target":{
                        "targetType":"page",
                        "url":"fuwu.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["5a02beb4347f4b5ca39ee529c7a20c2c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["5a02beb4347f4b5ca39ee529c7a20c2c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"d0a80bafb9a848aba7b96d9d57847f5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":656,
              "y":24},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e45df33ca5b4b58b8abe8c89bacf90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":656,
                  "y":24},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"99dc72b37fe447cbb2731cf02bdaab46",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":508,
              "y":43},
            "size":{
              "width":27,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/tuandui/1_u18_line.png"}},
{
          "id":"5a02beb4347f4b5ca39ee529c7a20c2c",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":600,
              "y":43},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"474315e1718b4265a00b1be1e7c01a5f",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":678,
              "y":43},
            "size":{
              "width":25,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"4dca57a35e1a490d91dad3f5db40f893",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":150},
            "size":{
              "width":242,
              "height":390},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7acc6367f64661a485e490c0c0b90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":150},
                "size":{
                  "width":242,
                  "height":390},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u21.png"}},
{
          "id":"89202d3a7a404aa1b52f445055fafdcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":150},
            "size":{
              "width":242,
              "height":390},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68329ca141254756ad29cc15ec4fed30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":150},
                "size":{
                  "width":242,
                  "height":390},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u21.png"}},
{
          "id":"1d05f0e906414f9993182bd7d3fd5f85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":180},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f919811abb4b4cb53bcf1b9b5080ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":180},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u25.png"}},
{
          "id":"9053b508d8934f93b17a0cb10ae2b1fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":615,
              "y":180},
            "size":{
              "width":112,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb800e5d9a241dc9f5d3800595bca3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":615,
                  "y":180},
                "size":{
                  "width":112,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u27.png"}},
{
          "id":"481f18474e084ba1a5e2bc0d016d8d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":305.5,
              "y":310},
            "size":{
              "width":107,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"366ab11a746140b18dba4e90063be88e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":305.5,
                  "y":310},
                "size":{
                  "width":107,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f539a8f938da4cfc93334f7c5a463eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":287,
              "y":350},
            "size":{
              "width":144,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e46e7f35ec48d2b599c3205fa46259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":350},
                "size":{
                  "width":144,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0b1d47c40543debccc749ffcd262b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":252,
              "y":390},
            "size":{
              "width":213,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58e82c5f7d246a7a9c30509eebbc4ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":252,
                  "y":390},
                "size":{
                  "width":213,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c04187a50d79443f9bf596f29f3e4493",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":592,
              "y":310},
            "size":{
              "width":157,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef42bbb65184d34ad4779c4abe0b4cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":592,
                  "y":310},
                "size":{
                  "width":157,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e8c7d790674ed39195c9383af77c4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":576,
              "y":350},
            "size":{
              "width":189,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9254ad12f8430cac9b867cb3c1c9d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":576,
                  "y":350},
                "size":{
                  "width":189,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e248a8096844add98f84e5821885c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":564,
              "y":390},
            "size":{
              "width":213,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcaf639e39384ba3963d886e16c7dc58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":564,
                  "y":390},
                "size":{
                  "width":213,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e6661492e1c4823818a9d6e443ca6e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":629},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb6c5f198684e4cabfe4788306fe190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":629},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u41.png"}},
{
          "id":"be0d4fac1d9d4fc892c8cac0481c5a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":132,
              "y":760},
            "size":{
              "width":78,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6435e7ccb5d34c99bc2de17af8597125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":132,
                  "y":760},
                "size":{
                  "width":78,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b52495264cb641358e268a2ab07af9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":126,
              "y":796},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"421c3b0803674d42a07189c627077727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":126,
                  "y":796},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10914917722c4386a5dca0547cc93ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":304,
              "y":631},
            "size":{
              "width":185,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757ebc47ee3044fbb74bd0766174fc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":304,
                  "y":631},
                "size":{
                  "width":185,
                  "height":179}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97dd6afa125d4102bfe92cd84923e809",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":629},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49999ff1f171489c88fe433eac8a653a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":629},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u49.png"}},
{
          "id":"b4a6c73a52ba44998e7462708b3020ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":539,
              "y":760},
            "size":{
              "width":185,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c6234a33974dc29d99ca8b38569978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":539,
                  "y":760},
                "size":{
                  "width":185,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16daf8ddacba4ba7b31f65a5824721bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":564,
              "y":796},
            "size":{
              "width":141,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cb97395d53649f1ab4e9ca37eda9d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":796},
                "size":{
                  "width":141,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5df480cae80425f9c751064c1b44e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":750,
              "y":631},
            "size":{
              "width":185,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9ec96750824941af56a5481c46b0a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":750,
                  "y":631},
                "size":{
                  "width":185,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a60e88cd41d471ca97291cd84638b20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":918},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"437715e8cab04ca899f5ff6e4cb568d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":918},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u57.jpg"}},
{
          "id":"765bb8e7c85844edb2f79a8292861564",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":591,
              "y":1059},
            "size":{
              "width":78,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e06b4259d6a4464bad057aee6cabdd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":591,
                  "y":1059},
                "size":{
                  "width":78,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6d6fda4d5c743059216ceaff342ecd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":571,
              "y":1097},
            "size":{
              "width":122,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88c9218726a8442889daa09a73561e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":1097},
                "size":{
                  "width":122,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e8f4200e9164f6db2a6ca5c643a8719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":750,
              "y":937},
            "size":{
              "width":185,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6789012f5c594f9e817878eb6b9c715c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":750,
                  "y":937},
                "size":{
                  "width":185,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82b3ab2fd9e40cfab3f64d8416d64ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":918},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae1d1923f0c4dbe9a54b268ad17820e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":918},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u65.png"}},
{
          "id":"a3729275ae044937b3f151c6e851e087",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":121,
              "y":1059},
            "size":{
              "width":101,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b69b7dccd24a1786fe715b7e93d3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":121,
                  "y":1059},
                "size":{
                  "width":101,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc714abfaa5f4932ae9b30382f1006e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":141,
              "y":1091},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8a9cb1b1ef49368f3ccd936728d224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":1091},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dfc8aec2fb4e189545ada82e87fd25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":297,
              "y":926},
            "size":{
              "width":185,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472ce1366c604c12a7e34fabd7af92c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":297,
                  "y":926},
                "size":{
                  "width":185,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cca81a5ee53549a5b2f36d8f12966bf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":1215},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74919b441db480eac4667e2606c533d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":1215},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u73.png"}},
{
          "id":"024c5544bb8a4741b41753d2ab993057",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":130,
              "y":1353},
            "size":{
              "width":101,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32f718e85c44498ca4751f4e1a2fd0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":130,
                  "y":1353},
                "size":{
                  "width":101,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f7ae7b3c8b145a994271daaa779f507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":151,
              "y":1389},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fa983566014490999877b24a8bbbcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":1389},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9545f1963f45eca44567557ba9dca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":301,
              "y":1196},
            "size":{
              "width":185,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e30a14b698b4a37af792bbc9ec21a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":301,
                  "y":1196},
                "size":{
                  "width":185,
                  "height":179}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51e3805d1b9d4452be04be286442a25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":1500},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46881abdd7c1416eaff20921990188de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":1500},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u68.png"}},
{
          "id":"0c7bc6d7722c4c4c991f37283ca07b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":1600},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63df6fb1831146d2a7c76c6981e89a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":1600},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u72.png"}},
{
          "id":"ea73abcb7edc402da1a2c36f7750414b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":295,
              "y":530},
            "size":{
              "width":128,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf9b46afdbb4334b8f123948a3da2c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":295,
                  "y":530},
                "size":{
                  "width":128,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u85.png"}},
{
          "id":"1ac93d7ed3804714806c5edab9b67cd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":606,
              "y":530},
            "size":{
              "width":128,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3765ca988b4e549f8f9dcc826f8666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":606,
                  "y":530},
                "size":{
                  "width":128,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u85.png"}},
{
          "id":"25dc27a4f9db48988cf800124a798864",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":843,
              "y":25},
            "size":{
              "width":58,
              "height":22},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0840de9558974886970ade2250d23d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":843,
                  "y":25},
                "size":{
                  "width":58,
                  "height":22},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u74.png"}},
{
          "id":"1d413d58951348f6a13438d92e3a0481",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":846,
              "y":26},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4e8ad7109a47d6beaa50fa4d2cce12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":846,
                  "y":26},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u76.png"}},
{
          "id":"5e6e80259c29473495bbd57ca7c37644",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":850,
              "y":28},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5a93a4e99141e69c1583cfe5622ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":850,
                  "y":28},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9650c6ac11044a4be83ce1897e1b3cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":874,
              "y":28},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0150827eec564b83a344b2efce8bcccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":28},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuanduiEN",
                      "target":{
                        "targetType":"page",
                        "url":"tuanduien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"128a97b01d3b43bc85b32fda6be4ae1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":745,
              "y":24},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6884d4a1ac44158aad4d9e953aa5de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":745,
                  "y":24},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 lianxi",
                      "target":{
                        "targetType":"page",
                        "url":"lianxi.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["1a9b3b22c2544f8c9cc249ca0354ac7d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["1a9b3b22c2544f8c9cc249ca0354ac7d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["474315e1718b4265a00b1be1e7c01a5f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1a9b3b22c2544f8c9cc249ca0354ac7d",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":758,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u90_line.png"}},
{
          "id":"21b3401af90340eeaf86fc341d47ac76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":1542},
            "size":{
              "width":398,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490f6e7bbd85404eb453ec591dcba0b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":1542},
                "size":{
                  "width":398,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1832d8bace4a4fc3aa3b071a2b2321e0":{
      "scriptId":"u0"},
    "2f819bbe2d0c43978918025840e4f24e":{
      "scriptId":"u1"},
    "8ed3ca659b0d475fb031622ef2403c17":{
      "scriptId":"u2"},
    "172027704ab74c2ab1787cff59f8fd63":{
      "scriptId":"u3"},
    "0eacfd3b90a14cae987498e225faca25":{
      "scriptId":"u4"},
    "cf12027bc4a04343915b1d2fe39ece17":{
      "scriptId":"u5"},
    "d421171a451f47ca9d4470248c495d6a":{
      "scriptId":"u6"},
    "36c03c2c140f48ffa9d71d1ca8d9e6e5":{
      "scriptId":"u7"},
    "12f086fa2bc54f0cbec9a5ab0919ea52":{
      "scriptId":"u8"},
    "27313ce8de1f443d9751fe988ea51306":{
      "scriptId":"u9"},
    "19672da44e87406f8c4f0c150929ef99":{
      "scriptId":"u10"},
    "2219cdf541fc4955b92cec284e82a433":{
      "scriptId":"u11"},
    "9ac174f0738747efb733ea840fb10c0c":{
      "scriptId":"u12"},
    "a4b9d3e150cc4d8eac164e38cfc4f4a3":{
      "scriptId":"u13"},
    "ec3118200757408dbfbb967a741d8b2b":{
      "scriptId":"u14"},
    "183aba501981460a98bb0ddc109ce063":{
      "scriptId":"u15"},
    "d0a80bafb9a848aba7b96d9d57847f5d":{
      "scriptId":"u16"},
    "4e45df33ca5b4b58b8abe8c89bacf90c":{
      "scriptId":"u17"},
    "99dc72b37fe447cbb2731cf02bdaab46":{
      "scriptId":"u18"},
    "5a02beb4347f4b5ca39ee529c7a20c2c":{
      "scriptId":"u19"},
    "474315e1718b4265a00b1be1e7c01a5f":{
      "scriptId":"u20"},
    "4dca57a35e1a490d91dad3f5db40f893":{
      "scriptId":"u21"},
    "1d7acc6367f64661a485e490c0c0b90c":{
      "scriptId":"u22"},
    "89202d3a7a404aa1b52f445055fafdcc":{
      "scriptId":"u23"},
    "68329ca141254756ad29cc15ec4fed30":{
      "scriptId":"u24"},
    "1d05f0e906414f9993182bd7d3fd5f85":{
      "scriptId":"u25"},
    "15f919811abb4b4cb53bcf1b9b5080ca":{
      "scriptId":"u26"},
    "9053b508d8934f93b17a0cb10ae2b1fa":{
      "scriptId":"u27"},
    "feb800e5d9a241dc9f5d3800595bca3a":{
      "scriptId":"u28"},
    "481f18474e084ba1a5e2bc0d016d8d92":{
      "scriptId":"u29"},
    "366ab11a746140b18dba4e90063be88e":{
      "scriptId":"u30"},
    "f539a8f938da4cfc93334f7c5a463eea":{
      "scriptId":"u31"},
    "31e46e7f35ec48d2b599c3205fa46259":{
      "scriptId":"u32"},
    "6b0b1d47c40543debccc749ffcd262b9":{
      "scriptId":"u33"},
    "d58e82c5f7d246a7a9c30509eebbc4ff":{
      "scriptId":"u34"},
    "c04187a50d79443f9bf596f29f3e4493":{
      "scriptId":"u35"},
    "8ef42bbb65184d34ad4779c4abe0b4cb":{
      "scriptId":"u36"},
    "43e8c7d790674ed39195c9383af77c4e":{
      "scriptId":"u37"},
    "fd9254ad12f8430cac9b867cb3c1c9d5":{
      "scriptId":"u38"},
    "4e248a8096844add98f84e5821885c39":{
      "scriptId":"u39"},
    "bcaf639e39384ba3963d886e16c7dc58":{
      "scriptId":"u40"},
    "9e6661492e1c4823818a9d6e443ca6e5":{
      "scriptId":"u41"},
    "4fb6c5f198684e4cabfe4788306fe190":{
      "scriptId":"u42"},
    "be0d4fac1d9d4fc892c8cac0481c5a93":{
      "scriptId":"u43"},
    "6435e7ccb5d34c99bc2de17af8597125":{
      "scriptId":"u44"},
    "b52495264cb641358e268a2ab07af9e3":{
      "scriptId":"u45"},
    "421c3b0803674d42a07189c627077727":{
      "scriptId":"u46"},
    "10914917722c4386a5dca0547cc93ac7":{
      "scriptId":"u47"},
    "757ebc47ee3044fbb74bd0766174fc87":{
      "scriptId":"u48"},
    "97dd6afa125d4102bfe92cd84923e809":{
      "scriptId":"u49"},
    "49999ff1f171489c88fe433eac8a653a":{
      "scriptId":"u50"},
    "b4a6c73a52ba44998e7462708b3020ed":{
      "scriptId":"u51"},
    "32c6234a33974dc29d99ca8b38569978":{
      "scriptId":"u52"},
    "16daf8ddacba4ba7b31f65a5824721bf":{
      "scriptId":"u53"},
    "8cb97395d53649f1ab4e9ca37eda9d1c":{
      "scriptId":"u54"},
    "c5df480cae80425f9c751064c1b44e21":{
      "scriptId":"u55"},
    "8e9ec96750824941af56a5481c46b0a8":{
      "scriptId":"u56"},
    "0a60e88cd41d471ca97291cd84638b20":{
      "scriptId":"u57"},
    "437715e8cab04ca899f5ff6e4cb568d9":{
      "scriptId":"u58"},
    "765bb8e7c85844edb2f79a8292861564":{
      "scriptId":"u59"},
    "2e06b4259d6a4464bad057aee6cabdd3":{
      "scriptId":"u60"},
    "f6d6fda4d5c743059216ceaff342ecd1":{
      "scriptId":"u61"},
    "88c9218726a8442889daa09a73561e6a":{
      "scriptId":"u62"},
    "6e8f4200e9164f6db2a6ca5c643a8719":{
      "scriptId":"u63"},
    "6789012f5c594f9e817878eb6b9c715c":{
      "scriptId":"u64"},
    "d82b3ab2fd9e40cfab3f64d8416d64ab":{
      "scriptId":"u65"},
    "6ae1d1923f0c4dbe9a54b268ad17820e":{
      "scriptId":"u66"},
    "a3729275ae044937b3f151c6e851e087":{
      "scriptId":"u67"},
    "c9b69b7dccd24a1786fe715b7e93d3da":{
      "scriptId":"u68"},
    "fc714abfaa5f4932ae9b30382f1006e4":{
      "scriptId":"u69"},
    "1f8a9cb1b1ef49368f3ccd936728d224":{
      "scriptId":"u70"},
    "a5dfc8aec2fb4e189545ada82e87fd25":{
      "scriptId":"u71"},
    "472ce1366c604c12a7e34fabd7af92c7":{
      "scriptId":"u72"},
    "cca81a5ee53549a5b2f36d8f12966bf3":{
      "scriptId":"u73"},
    "e74919b441db480eac4667e2606c533d":{
      "scriptId":"u74"},
    "024c5544bb8a4741b41753d2ab993057":{
      "scriptId":"u75"},
    "32f718e85c44498ca4751f4e1a2fd0b1":{
      "scriptId":"u76"},
    "9f7ae7b3c8b145a994271daaa779f507":{
      "scriptId":"u77"},
    "d0fa983566014490999877b24a8bbbcc":{
      "scriptId":"u78"},
    "0e9545f1963f45eca44567557ba9dca4":{
      "scriptId":"u79"},
    "7e30a14b698b4a37af792bbc9ec21a4f":{
      "scriptId":"u80"},
    "51e3805d1b9d4452be04be286442a25e":{
      "scriptId":"u81"},
    "46881abdd7c1416eaff20921990188de":{
      "scriptId":"u82"},
    "0c7bc6d7722c4c4c991f37283ca07b42":{
      "scriptId":"u83"},
    "63df6fb1831146d2a7c76c6981e89a8b":{
      "scriptId":"u84"},
    "ea73abcb7edc402da1a2c36f7750414b":{
      "scriptId":"u85"},
    "fbf9b46afdbb4334b8f123948a3da2c4":{
      "scriptId":"u86"},
    "1ac93d7ed3804714806c5edab9b67cd1":{
      "scriptId":"u87"},
    "ed3765ca988b4e549f8f9dcc826f8666":{
      "scriptId":"u88"},
    "25dc27a4f9db48988cf800124a798864":{
      "scriptId":"u89"},
    "0840de9558974886970ade2250d23d48":{
      "scriptId":"u90"},
    "1d413d58951348f6a13438d92e3a0481":{
      "scriptId":"u91"},
    "3a4e8ad7109a47d6beaa50fa4d2cce12":{
      "scriptId":"u92"},
    "5e6e80259c29473495bbd57ca7c37644":{
      "scriptId":"u93"},
    "3e5a93a4e99141e69c1583cfe5622ec2":{
      "scriptId":"u94"},
    "b9650c6ac11044a4be83ce1897e1b3cd":{
      "scriptId":"u95"},
    "0150827eec564b83a344b2efce8bcccc":{
      "scriptId":"u96"},
    "128a97b01d3b43bc85b32fda6be4ae1e":{
      "scriptId":"u97"},
    "de6884d4a1ac44158aad4d9e953aa5de":{
      "scriptId":"u98"},
    "1a9b3b22c2544f8c9cc249ca0354ac7d":{
      "scriptId":"u99"},
    "21b3401af90340eeaf86fc341d47ac76":{
      "scriptId":"u100"},
    "490f6e7bbd85404eb453ec591dcba0b2":{
      "scriptId":"u101"}}});