$axure.loadCurrentPage({
  "url":"huanjian.html",
  "generationDate":new Date(1464657948594.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"11b0bfd3ff07427791996d2e77f87fd0",
    "type":"Axure:Page",
    "name":"huanjian",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e576bd898dd04563aca8518d6384603d",
          "label":"beijing",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c74daa4b3d482cb005af3ceeb7288b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/beijing_u0.jpg"}},
{
          "id":"2c6b9c8861924059bebe4e2b8bdccdb1",
          "label":"logo",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":18},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e322d3cf9d4130a2b881206bb29378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":18},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/logo_u2.png"}},
{
          "id":"9f4c9bcf679c47b1949617b425c5950f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Cambria Math Regular', 'Cambria Math'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":249,
              "y":21},
            "size":{
              "width":149,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc920e45e167403b9c680aa5046e7706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Cambria Math Regular', 'Cambria Math'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":249,
                  "y":21},
                "size":{
                  "width":149,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29e99270a1914d01bf0ce7677b89a262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":570,
              "y":30},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1593b7d004f744a6b42e81959e6cb835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":570,
                  "y":30},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["03db5dccb77e4d258dcada04150546d7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"44f99184f66245e4bd1d7b8108dbc48c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":680,
              "y":30},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb98090976a341cc89a3e5b4e4ec42e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":680,
                  "y":30},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["7f88c6b0ba5d46368fecaf79abd18eb8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["03db5dccb77e4d258dcada04150546d7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["7f88c6b0ba5d46368fecaf79abd18eb8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9d24b3a56660402db97497d01154ce35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":796,
              "y":30},
            "size":{
              "width":74,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab82f0da571c4b2ba48aeb0ef40983fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":796,
                  "y":30},
                "size":{
                  "width":74,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["5594ff57f8634d948b8b48aeb3badcd4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["03db5dccb77e4d258dcada04150546d7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["5594ff57f8634d948b8b48aeb3badcd4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c7a83b13091a45288ba7bf64ece4ed5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":907,
              "y":30},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a4505ceb9d24915b1e7b6c10f9ee318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":907,
                  "y":30},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["4f20c4d0f3e44d31bd2cfc4122b5fc02"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["03db5dccb77e4d258dcada04150546d7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["4f20c4d0f3e44d31bd2cfc4122b5fc02"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["03db5dccb77e4d258dcada04150546d7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"03db5dccb77e4d258dcada04150546d7",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":49},
            "size":{
              "width":25,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/1_u14_line.png"}},
{
          "id":"7f88c6b0ba5d46368fecaf79abd18eb8",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":700.5,
              "y":49},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/1_u14_line.png"}},
{
          "id":"5594ff57f8634d948b8b48aeb3badcd4",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":820.5,
              "y":49},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/1_u14_line.png"}},
{
          "id":"4f20c4d0f3e44d31bd2cfc4122b5fc02",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":921,
              "y":49},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/1_u14_line.png"}},
{
          "id":"4b53ee0af5034dd7986729a1e43649b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":688,
              "height":266},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f8e3e1ef71e4a4cacde53d77ee94fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":688,
                  "height":266},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u18.png"}},
{
          "id":"6eba2e8e32924bd6bdaa3ce8c24c1e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":271},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a6ff7f463d48efa1cfa6044121cb08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":271},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u20.png"}},
{
          "id":"20ba5152d12e4777a2a8c50feabb45b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":323},
            "size":{
              "width":54,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d4a7cd1c5124bc1a1151ba4b977aeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":323},
                "size":{
                  "width":54,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u22.png"}},
{
          "id":"22c5ffa6543f40aea0b9c54fa1a458f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":618,
              "y":271},
            "size":{
              "width":201,
              "height":285},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"654a1444ff274c79849b4de4e5a43f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":618,
                  "y":271},
                "size":{
                  "width":201,
                  "height":285},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u24.png"}},
{
          "id":"bc4218edc9804759bab9f6b4c9b48805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF83F63,
              "opacity":1},
            "location":{
              "x":218,
              "y":394},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0f939b075744e2f8cb1b4c6cb888415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF83F63,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":394},
                "size":{
                  "width":105,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0a89d88ef04a119e24907e6af7d28e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":218,
              "y":417},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56977ce7c54644e9aef47e5d8119d834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":417},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e793fe0fd49c4982971110bccb20d1f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":218,
              "y":451},
            "size":{
              "width":334,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d3f6c3e06648a18ad4d0eb8f923a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":451},
                "size":{
                  "width":334,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1223877032a344d4bf68ff993af58f76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE4168,
              "opacity":1},
            "location":{
              "x":218,
              "y":532},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc47a9248e7847b19bc8184562606681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE4168,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":532},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec5e25346fc640949cb78b47987bbd82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":247,
              "y":532},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228446e1c63948c3af0978c520e29221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":532},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cac348de07c4345b291ab15ad6a07af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":614},
            "size":{
              "width":688,
              "height":266},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8b7376232c434cabc09d7d2cc8e343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":614},
                "size":{
                  "width":688,
                  "height":266},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u18.png"}},
{
          "id":"a1c18d2dfdee4847b05d73609f99268e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":600},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8045875de7854e00aad47f2311e22065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":600},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u20.png"}},
{
          "id":"297738ec169d4295bd8b8a6293df732a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":651},
            "size":{
              "width":54,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":8,
              "color":{
                "r":255,
                "g":102,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e098d68bf6ca46548b47e9073da915f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":651},
                "size":{
                  "width":54,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":8,
                  "color":{
                    "r":255,
                    "g":102,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u40.png"}},
{
          "id":"b4ac77f3b34349e1a8bab39ca7317045",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":199,
              "y":591},
            "size":{
              "width":201,
              "height":289},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a550ba715160460e8c73b6f5cc8754b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":591},
                "size":{
                  "width":201,
                  "height":289},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u42.png"}},
{
          "id":"1dbd9c74552a4de1a316f79f0e2a8f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF83F63,
              "opacity":1},
            "location":{
              "x":688,
              "y":720},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf834d3f0494567bf2318f77fbfb59b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF83F63,
                  "opacity":1},
                "location":{
                  "x":688,
                  "y":720},
                "size":{
                  "width":105,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2ec4a0c59c476d9bef08ba46956d94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":440,
              "y":771},
            "size":{
              "width":360,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd61b67113f42fbbb54644cc07fbf8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":771},
                "size":{
                  "width":360,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfd5d1d844c1478685a21d4e1c86e751",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE4168,
              "opacity":1},
            "location":{
              "x":757,
              "y":850},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e703407aabb84d44b048a7d8f9d14474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE4168,
                  "opacity":1},
                "location":{
                  "x":757,
                  "y":850},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e6a5dcbbebf4ee1bf4bbbf4f5182f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":785,
              "y":850},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4404cc742b5c46929f6123e8a75f7ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":785,
                  "y":850},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7758a63c7b164eb28837dfddea86f665",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":696,
              "y":742},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c99554ffb14f628240a7e1e7836e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":696,
                  "y":742},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b640e8b2fec648d8b048faac087d3fee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":930},
            "size":{
              "width":1024,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c3535c7489a4e6bbec52ba46b43b7d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":930},
                "size":{
                  "width":1024,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u54.png"}},
{
          "id":"09df7b73ba074340a7d73dc938cab1ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":1035},
            "size":{
              "width":167,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7055122a2ff84bc8b397b15390f9ba1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":173,
                  "y":1035},
                "size":{
                  "width":167,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u56.png"}},
{
          "id":"b6fbcd9c46574a86aa08999de0c7738e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":1035},
            "size":{
              "width":167,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da35dffaf2a845beb0c71e7f11c4ab46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":1035},
                "size":{
                  "width":167,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u58.png"}},
{
          "id":"4cca77058d8f474ab49b3c489d294116",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":206,
              "y":1201},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad58c1ee55045b98bef5bd5b49b0a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":206,
                  "y":1201},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13829491c8304045acf25957e864568c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":107,
              "y":1251},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f246db1a02f240e5967994d7964e6c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":1251},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"162148ee7877490ea99181d6a8f5503a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":617,
              "y":1255},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ae945ed25b4b4b9bee6a9baa1d66e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":1255},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a63b55e5078464a8f91c7b07f1a76c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":707,
              "y":1201},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11df8e409980400a8546c665a9840e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":707,
                  "y":1201},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a90827473b3a43a3b8cf6bf4873a8e9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":1389},
            "size":{
              "width":80,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6669c043a1e347f3a1013b1a2160e02d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":1389},
                "size":{
                  "width":80,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u68.png"}},
{
          "id":"726531201bd04d549fe372dbb855a3ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":1430},
            "size":{
              "width":243,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD6313E}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/u70_line.png"}},
{
          "id":"22d200b19e1b48ed9d6e5edeedf04508",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":1430},
            "size":{
              "width":243,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD6313E}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/huanjian/u70_line.png"}},
{
          "id":"a934c7e518b44a459c6c5e87845d3c3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":1510},
            "size":{
              "width":118,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d294c4abbe465599b3997e160f8a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":1510},
                "size":{
                  "width":118,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u72.png"}},
{
          "id":"384ec736baf1450383a86727fa3107e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":1510},
            "size":{
              "width":118,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e611dec862d41aa842f569f98ff7e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":1510},
                "size":{
                  "width":118,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u74.png"}},
{
          "id":"4df2e9b6539e47be9445591802ced6e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":733,
              "y":1510},
            "size":{
              "width":118,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4e069ae302451f9b95bdfbd8718964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":733,
                  "y":1510},
                "size":{
                  "width":118,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u76.png"}},
{
          "id":"f884585810c74401a67af4e05a79b091",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":1728},
            "size":{
              "width":118,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935cebdad52942b5ade580d6fd329a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":1728},
                "size":{
                  "width":118,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u78.png"}},
{
          "id":"c0b208a463884f13bcd93f3acea0d1d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":1728},
            "size":{
              "width":118,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb4903b3d0049dca87d20ee3dd6683d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":1728},
                "size":{
                  "width":118,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u80.png"}},
{
          "id":"7b82a1e6d4e248f184a8c332ca1113db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":1640},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a7feddeeb44e9693d4cdc7159b84d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":1640},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e7477ee562c4840b68585c3d91e6559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1640},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98540b4feb3144609ab71f665b7ed899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1640},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6e7faac5b99490ebd05c4fb3e6d7a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":1640},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9342a4c624684ee5b4a3d30de2922aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":1640},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5475f03be7475daf2d1cd9cf6f1cb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":1858},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95c09805724546ddb398267eee0a64c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":1858},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b480ac491fa405498ab472cf887e7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":1858},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ade7b13fa34059bec55ffcbf84eeb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":1858},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"277eba61411a46a196878da32013b4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":1930},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6065835e30cf48e2a006cd5570d825f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":1930},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u92.png"}},
{
          "id":"ab9497544dbb4e17b07e0e461e200cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":341,
              "y":1972},
            "size":{
              "width":341,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5632cc953b3d42faad569fae4af409b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":341,
                  "y":1972},
                "size":{
                  "width":341,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c45b794ce004741a5471afd972edd84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":2030},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22db71cc8994f239ad172c1c9d0cefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":2030},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/huanjian/u96.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e576bd898dd04563aca8518d6384603d":{
      "scriptId":"u0"},
    "37c74daa4b3d482cb005af3ceeb7288b":{
      "scriptId":"u1"},
    "2c6b9c8861924059bebe4e2b8bdccdb1":{
      "scriptId":"u2"},
    "59e322d3cf9d4130a2b881206bb29378":{
      "scriptId":"u3"},
    "9f4c9bcf679c47b1949617b425c5950f":{
      "scriptId":"u4"},
    "dc920e45e167403b9c680aa5046e7706":{
      "scriptId":"u5"},
    "29e99270a1914d01bf0ce7677b89a262":{
      "scriptId":"u6"},
    "1593b7d004f744a6b42e81959e6cb835":{
      "scriptId":"u7"},
    "44f99184f66245e4bd1d7b8108dbc48c":{
      "scriptId":"u8"},
    "eb98090976a341cc89a3e5b4e4ec42e5":{
      "scriptId":"u9"},
    "9d24b3a56660402db97497d01154ce35":{
      "scriptId":"u10"},
    "ab82f0da571c4b2ba48aeb0ef40983fe":{
      "scriptId":"u11"},
    "c7a83b13091a45288ba7bf64ece4ed5f":{
      "scriptId":"u12"},
    "4a4505ceb9d24915b1e7b6c10f9ee318":{
      "scriptId":"u13"},
    "03db5dccb77e4d258dcada04150546d7":{
      "scriptId":"u14"},
    "7f88c6b0ba5d46368fecaf79abd18eb8":{
      "scriptId":"u15"},
    "5594ff57f8634d948b8b48aeb3badcd4":{
      "scriptId":"u16"},
    "4f20c4d0f3e44d31bd2cfc4122b5fc02":{
      "scriptId":"u17"},
    "4b53ee0af5034dd7986729a1e43649b0":{
      "scriptId":"u18"},
    "2f8e3e1ef71e4a4cacde53d77ee94fb1":{
      "scriptId":"u19"},
    "6eba2e8e32924bd6bdaa3ce8c24c1e05":{
      "scriptId":"u20"},
    "75a6ff7f463d48efa1cfa6044121cb08":{
      "scriptId":"u21"},
    "20ba5152d12e4777a2a8c50feabb45b3":{
      "scriptId":"u22"},
    "1d4a7cd1c5124bc1a1151ba4b977aeeb":{
      "scriptId":"u23"},
    "22c5ffa6543f40aea0b9c54fa1a458f3":{
      "scriptId":"u24"},
    "654a1444ff274c79849b4de4e5a43f80":{
      "scriptId":"u25"},
    "bc4218edc9804759bab9f6b4c9b48805":{
      "scriptId":"u26"},
    "a0f939b075744e2f8cb1b4c6cb888415":{
      "scriptId":"u27"},
    "6b0a89d88ef04a119e24907e6af7d28e":{
      "scriptId":"u28"},
    "56977ce7c54644e9aef47e5d8119d834":{
      "scriptId":"u29"},
    "e793fe0fd49c4982971110bccb20d1f1":{
      "scriptId":"u30"},
    "b7d3f6c3e06648a18ad4d0eb8f923a09":{
      "scriptId":"u31"},
    "1223877032a344d4bf68ff993af58f76":{
      "scriptId":"u32"},
    "cc47a9248e7847b19bc8184562606681":{
      "scriptId":"u33"},
    "ec5e25346fc640949cb78b47987bbd82":{
      "scriptId":"u34"},
    "228446e1c63948c3af0978c520e29221":{
      "scriptId":"u35"},
    "3cac348de07c4345b291ab15ad6a07af":{
      "scriptId":"u36"},
    "fa8b7376232c434cabc09d7d2cc8e343":{
      "scriptId":"u37"},
    "a1c18d2dfdee4847b05d73609f99268e":{
      "scriptId":"u38"},
    "8045875de7854e00aad47f2311e22065":{
      "scriptId":"u39"},
    "297738ec169d4295bd8b8a6293df732a":{
      "scriptId":"u40"},
    "e098d68bf6ca46548b47e9073da915f0":{
      "scriptId":"u41"},
    "b4ac77f3b34349e1a8bab39ca7317045":{
      "scriptId":"u42"},
    "a550ba715160460e8c73b6f5cc8754b4":{
      "scriptId":"u43"},
    "1dbd9c74552a4de1a316f79f0e2a8f4a":{
      "scriptId":"u44"},
    "cdf834d3f0494567bf2318f77fbfb59b":{
      "scriptId":"u45"},
    "1e2ec4a0c59c476d9bef08ba46956d94":{
      "scriptId":"u46"},
    "7bd61b67113f42fbbb54644cc07fbf8f":{
      "scriptId":"u47"},
    "bfd5d1d844c1478685a21d4e1c86e751":{
      "scriptId":"u48"},
    "e703407aabb84d44b048a7d8f9d14474":{
      "scriptId":"u49"},
    "1e6a5dcbbebf4ee1bf4bbbf4f5182f07":{
      "scriptId":"u50"},
    "4404cc742b5c46929f6123e8a75f7ea0":{
      "scriptId":"u51"},
    "7758a63c7b164eb28837dfddea86f665":{
      "scriptId":"u52"},
    "a9c99554ffb14f628240a7e1e7836e3d":{
      "scriptId":"u53"},
    "b640e8b2fec648d8b048faac087d3fee":{
      "scriptId":"u54"},
    "6c3535c7489a4e6bbec52ba46b43b7d2":{
      "scriptId":"u55"},
    "09df7b73ba074340a7d73dc938cab1ef":{
      "scriptId":"u56"},
    "7055122a2ff84bc8b397b15390f9ba1b":{
      "scriptId":"u57"},
    "b6fbcd9c46574a86aa08999de0c7738e":{
      "scriptId":"u58"},
    "da35dffaf2a845beb0c71e7f11c4ab46":{
      "scriptId":"u59"},
    "4cca77058d8f474ab49b3c489d294116":{
      "scriptId":"u60"},
    "bad58c1ee55045b98bef5bd5b49b0a1f":{
      "scriptId":"u61"},
    "13829491c8304045acf25957e864568c":{
      "scriptId":"u62"},
    "f246db1a02f240e5967994d7964e6c8c":{
      "scriptId":"u63"},
    "162148ee7877490ea99181d6a8f5503a":{
      "scriptId":"u64"},
    "b7ae945ed25b4b4b9bee6a9baa1d66e6":{
      "scriptId":"u65"},
    "9a63b55e5078464a8f91c7b07f1a76c3":{
      "scriptId":"u66"},
    "11df8e409980400a8546c665a9840e2a":{
      "scriptId":"u67"},
    "a90827473b3a43a3b8cf6bf4873a8e9f":{
      "scriptId":"u68"},
    "6669c043a1e347f3a1013b1a2160e02d":{
      "scriptId":"u69"},
    "726531201bd04d549fe372dbb855a3ee":{
      "scriptId":"u70"},
    "22d200b19e1b48ed9d6e5edeedf04508":{
      "scriptId":"u71"},
    "a934c7e518b44a459c6c5e87845d3c3f":{
      "scriptId":"u72"},
    "14d294c4abbe465599b3997e160f8a81":{
      "scriptId":"u73"},
    "384ec736baf1450383a86727fa3107e3":{
      "scriptId":"u74"},
    "9e611dec862d41aa842f569f98ff7e8f":{
      "scriptId":"u75"},
    "4df2e9b6539e47be9445591802ced6e3":{
      "scriptId":"u76"},
    "8b4e069ae302451f9b95bdfbd8718964":{
      "scriptId":"u77"},
    "f884585810c74401a67af4e05a79b091":{
      "scriptId":"u78"},
    "935cebdad52942b5ade580d6fd329a31":{
      "scriptId":"u79"},
    "c0b208a463884f13bcd93f3acea0d1d7":{
      "scriptId":"u80"},
    "6fb4903b3d0049dca87d20ee3dd6683d":{
      "scriptId":"u81"},
    "7b82a1e6d4e248f184a8c332ca1113db":{
      "scriptId":"u82"},
    "a4a7feddeeb44e9693d4cdc7159b84d7":{
      "scriptId":"u83"},
    "7e7477ee562c4840b68585c3d91e6559":{
      "scriptId":"u84"},
    "98540b4feb3144609ab71f665b7ed899":{
      "scriptId":"u85"},
    "b6e7faac5b99490ebd05c4fb3e6d7a7f":{
      "scriptId":"u86"},
    "9342a4c624684ee5b4a3d30de2922aa6":{
      "scriptId":"u87"},
    "3a5475f03be7475daf2d1cd9cf6f1cb5":{
      "scriptId":"u88"},
    "95c09805724546ddb398267eee0a64c8":{
      "scriptId":"u89"},
    "5b480ac491fa405498ab472cf887e7df":{
      "scriptId":"u90"},
    "a5ade7b13fa34059bec55ffcbf84eeb3":{
      "scriptId":"u91"},
    "277eba61411a46a196878da32013b4e8":{
      "scriptId":"u92"},
    "6065835e30cf48e2a006cd5570d825f1":{
      "scriptId":"u93"},
    "ab9497544dbb4e17b07e0e461e200cf0":{
      "scriptId":"u94"},
    "5632cc953b3d42faad569fae4af409b1":{
      "scriptId":"u95"},
    "4c45b794ce004741a5471afd972edd84":{
      "scriptId":"u96"},
    "f22db71cc8994f239ad172c1c9d0cefb":{
      "scriptId":"u97"}}});